## Settings
title: NerdUbeezy
owner: "Jeff Ubayi"
url: "https://akiritsu.github.io"
baseurl: "/pRoJEct-NeGYa"
permalink: /:title/
description: "A blog about hacking"
base: "https://nerdubeezy.netlify.app/"
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "jeffubayi@gmail.com"
github: "jeffubayi"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Designed by Jeff Ubayi"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"
